version: '3.8'
services:
  service-a:
    build:
      context: ./service-a
    image: cosmo-bun-apollo-server:service-a
    ports:
      - '4501:4501'

  service-b:
    build:
      context: ./service-b
    image: cosmo-bun-apollo-server:service-b
    ports:
      - '4502:4502'

  cosmo-router:
    image: ghcr.io/wundergraph/cosmo/router:0.61.1
    container_name: cosmo-bun-apollo-server-router
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4500:4500"
    volumes:
      - ./config.json:/config.json
    environment:
      - ROUTER_CONFIG_PATH=./config.json
      - LISTEN_ADDR=0.0.0.0:4500
      - LOG_LEVEL=debug
      - DEV_MODE=true
